title: BioUno
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Open Source Software for Scientific Applications
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://biouno.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: biouno
github_username:  biouno

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

theme: minimal-mistakes-jekyll
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
