title: BioUno
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Open Source Software for Scientific Applications
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://biouno.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: biouno
github_username:  biouno

# Build settings
markdown: kramdown

remote_theme: "mmistakes/minimal-mistakes@4.19.0"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

include:
  - "_pages"
  - "favicon.ico"

defaults:
  # all
  - scope:
      path: ""
    values:
      sidebar:
        nav: "docs"
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development

paginate: 5
paginate_path: "blog/page:num/"
