---
layout: page
title: Using the figshare Plug-in
---

<p>
	The figshare plug-in is available from our
	<a href="http://biouno.org/jenkins-update-site.html">update center</a>.
	It integrates Jenkins and <a href="http://figshare.com">figshare</a>.
</p>

<p>
	The first thing you have to do is set up an Application in figshare to
	allow Jenkins to talk to figshare. You can do that by clicking on your user
	name, and going to Applications. Then give it a name and fill the other details. 
	The Access codes tab will be automatic generated for you, but you still have
	to change the permissions.
</p>

<p>
	Since Jenkins will be creating articles and uploading images, your application
	needs full read and write access.
</p>

<p class="center">
	<a href="{{ site.baseurl }}assets/img/tutorials/using-the-figshare-plugin/screenshot_figshare_001.png"> <img src="{{ site.baseurl }}assets/img/tutorials/using-the-figshare-plugin/screenshot_figshare_001.png">
	</a>
</p>

<p>
	After you've installed the plug-in and created the Application in figshare, you
	will need to add a <a href="https://wiki.jenkins-ci.org/display/JENKINS/Credentials+Plugin">Credential</a>
	in Jenkins. Use the data generated by figshare in your Application's Access codes tab
	in your credential.
</p>

<p class="center">
	<a href="{{ site.baseurl }}assets/img/tutorials/using-the-figshare-plugin/screenshot_figshare_002.png"> <img src="{{ site.baseurl }}assets/img/tutorials/using-the-figshare-plugin/screenshot_figshare_002.png">
	</a>
</p>

<p>
	Finally you can add a post build step to your job, and publish artefacts to
	figshare. Use the credentials that you created earlier, and a pattern that
	will match the files that you want to upload to figshare.
</p>

<p class="center">
	<a href="{{ site.baseurl }}assets/img/tutorials/using-the-figshare-plugin/screenshot_figshare_003.png"> <img src="{{ site.baseurl }}assets/img/tutorials/using-the-figshare-plugin/screenshot_figshare_003.png">
	</a>
</p>

<p class="center">
	<a href="{{ site.baseurl }}assets/img/tutorials/using-the-figshare-plugin/screenshot_figshare_004.png"> <img src="{{ site.baseurl }}assets/img/tutorials/using-the-figshare-plugin/screenshot_figshare_004.png">
	</a>
</p>

<p>Now go to figshare.com and review your articles.</p>

<p class="center">
	<a href="{{ site.baseurl }}assets/img/tutorials/using-the-figshare-plugin/screenshot_figshare_005.png"> <img src="{{ site.baseurl }}assets/img/tutorials/using-the-figshare-plugin/screenshot_figshare_005.png">
	</a>
</p>
